# Modified by zhiyb (Yubo Zhi)

TRG	= ADC_DAC_PWM
SRC	= mainDADC.c dac.c adc.c

PRGER	= usbasp
MCU_TARGET	= atmega644p
MCU_FREQ	= 12000000

EFUSE	= 0xFF
HFUSE	= 0x9C
LFUSE	= 0xE7

include ../Makefile_AVR.defs
